@startuml

class compte{
    -id: int
    -pseudo: string
    -email: string
    -password: string
}

class jdr{
    -id: int
    -nom: string
    -description: string
    -date_prochaine_seance: date
}

class notification{
    -id: int
    -titre: string
    -message: string
    -restriction: int
}

class records{
    -name: string
    -record: record[]
}

interface record{
    -title: string
    -players: string[]
    -highscore: string
}

class joueur{
    -flowers: int
}

class mj{
    -flowers: int

}

class admin{
    -flowers: int
}

compte <|-- admin
compte <|-- joueur
compte <|-- mj

joueur "1..*" --  "0..*" jdr
mj "1" --  "0..*" jdr

mj "1" -- "0..*" notification
admin "1" -- "0..*" notification

mj "1..*" -- "0..*" record
admin "1..*" -- "0..*" record

@enduml